// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: event.proto

package contract

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Event struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// event_type: The type of the transaction like 'slash' or 'unstake'
	EventType string `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"eventType"` // @gotags: json:"eventType"
	// msg: The actual event message payload, which is encapsulated in a oneof format
	//
	// Types that are valid to be assigned to Msg:
	//
	//	*Event_Custom
	Msg isEvent_Msg `protobuf_oneof:"msg"`
	// height: the block height of the event
	Height uint64 `protobuf:"varint,91,opt,name=height,proto3" json:"height,omitempty"`
	// reference: the 'begin_block' / transaction hash / 'end_block'
	Reference string `protobuf:"bytes,92,opt,name=reference,proto3" json:"reference,omitempty"`
	// chainId: the chain id associated with the event
	ChainId uint64 `protobuf:"varint,93,opt,name=chainId,proto3" json:"chainId,omitempty"`
	// block_height: the number of blocks in the blockchain before a specific block, indicating its position in the chain
	// and representing the blockchain's length
	BlockHeight uint64 `protobuf:"varint,94,opt,name=block_height,json=blockHeight,proto3" json:"blockHeight"` // @gotags: json:"blockHeight"
	// block_hash: a unique identifier for a block, generated by applying a cryptographic hash function to the block's contents,
	// ensuring its integrity and connecting it to the previous block in the chain.
	BlockHash []byte `protobuf:"bytes,95,opt,name=block_hash,json=blockHash,proto3" json:"blockHash"` // @gotags: json:"blockHash"
	// address: The address of the user affected by the event
	Address       []byte `protobuf:"bytes,96,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *Event) GetMsg() isEvent_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *Event) GetCustom() *EventCustom {
	if x != nil {
		if x, ok := x.Msg.(*Event_Custom); ok {
			return x.Custom
		}
	}
	return nil
}

func (x *Event) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Event) GetReference() string {
	if x != nil {
		return x.Reference
	}
	return ""
}

func (x *Event) GetChainId() uint64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *Event) GetBlockHeight() uint64 {
	if x != nil {
		return x.BlockHeight
	}
	return 0
}

func (x *Event) GetBlockHash() []byte {
	if x != nil {
		return x.BlockHash
	}
	return nil
}

func (x *Event) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

type isEvent_Msg interface {
	isEvent_Msg()
}

type Event_Custom struct {
	Custom *EventCustom `protobuf:"bytes,11,opt,name=custom,proto3,oneof"`
}

func (*Event_Custom) isEvent_Msg() {}

// EventCustom carries a plugin-defined event payload.
type EventCustom struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// msg: custom payload.
	Msg           *anypb.Any `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventCustom) Reset() {
	*x = EventCustom{}
	mi := &file_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventCustom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventCustom) ProtoMessage() {}

func (x *EventCustom) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventCustom.ProtoReflect.Descriptor instead.
func (*EventCustom) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{1}
}

func (x *EventCustom) GetMsg() *anypb.Any {
	if x != nil {
		return x.Msg
	}
	return nil
}

var File_event_proto protoreflect.FileDescriptor

const file_event_proto_rawDesc = "" +
	"\n" +
	"\vevent.proto\x12\x05types\x1a\x19google/protobuf/any.proto\"\x87\x02\n" +
	"\x05Event\x12\x1d\n" +
	"\n" +
	"event_type\x18\x01 \x01(\tR\teventType\x12,\n" +
	"\x06custom\x18\v \x01(\v2\x12.types.EventCustomH\x00R\x06custom\x12\x16\n" +
	"\x06height\x18[ \x01(\x04R\x06height\x12\x1c\n" +
	"\treference\x18\\ \x01(\tR\treference\x12\x18\n" +
	"\achainId\x18] \x01(\x04R\achainId\x12!\n" +
	"\fblock_height\x18^ \x01(\x04R\vblockHeight\x12\x1d\n" +
	"\n" +
	"block_hash\x18_ \x01(\fR\tblockHash\x12\x18\n" +
	"\aaddress\x18` \x01(\fR\aaddressB\x05\n" +
	"\x03msg\"5\n" +
	"\vEventCustom\x12&\n" +
	"\x03msg\x18\x01 \x01(\v2\x14.google.protobuf.AnyR\x03msgB3Z1github.com/canopy-network/go-plugin-test/contractb\x06proto3"

var (
	file_event_proto_rawDescOnce sync.Once
	file_event_proto_rawDescData []byte
)

func file_event_proto_rawDescGZIP() []byte {
	file_event_proto_rawDescOnce.Do(func() {
		file_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_event_proto_rawDesc), len(file_event_proto_rawDesc)))
	})
	return file_event_proto_rawDescData
}

var file_event_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_event_proto_goTypes = []any{
	(*Event)(nil),       // 0: types.Event
	(*EventCustom)(nil), // 1: types.EventCustom
	(*anypb.Any)(nil),   // 2: google.protobuf.Any
}
var file_event_proto_depIdxs = []int32{
	1, // 0: types.Event.custom:type_name -> types.EventCustom
	2, // 1: types.EventCustom.msg:type_name -> google.protobuf.Any
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_event_proto_init() }
func file_event_proto_init() {
	if File_event_proto != nil {
		return
	}
	file_event_proto_msgTypes[0].OneofWrappers = []any{
		(*Event_Custom)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_event_proto_rawDesc), len(file_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_event_proto_goTypes,
		DependencyIndexes: file_event_proto_depIdxs,
		MessageInfos:      file_event_proto_msgTypes,
	}.Build()
	File_event_proto = out.File
	file_event_proto_goTypes = nil
	file_event_proto_depIdxs = nil
}
