// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: store.proto

package lib

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *****************************************************************************************************
// This file is auto-generated from source files in `/lib/.proto/*` using Protocol Buffers (protobuf)
//
// Protobuf is a language-neutral, platform-neutral serialization format. It allows users
// to define objects in a way that’s both efficient to store and fast to transmit over the network.
// These definitions are compiled into code that *enables different systems and programming languages
// to communicate in a byte-perfect manner*
//
// To update these structures, make changes to the source .proto files, then recompile
// to regenerate this file.
// These auto-generated files are easily recognized by checking for a `.pb.go` ending
// *****************************************************************************************************
// _
// _
// _
// CommitID is a structure that holds the merkle root for a certain height
type CommitID struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// height: the identifier of the commit_id referencing the block height
	Height uint64 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	// root: the merkle root of the SMT state commit store
	Root          []byte `protobuf:"bytes,2,opt,name=root,proto3" json:"root,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitID) Reset() {
	*x = CommitID{}
	mi := &file_store_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitID) ProtoMessage() {}

func (x *CommitID) ProtoReflect() protoreflect.Message {
	mi := &file_store_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitID.ProtoReflect.Descriptor instead.
func (*CommitID) Descriptor() ([]byte, []int) {
	return file_store_proto_rawDescGZIP(), []int{0}
}

func (x *CommitID) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *CommitID) GetRoot() []byte {
	if x != nil {
		return x.Root
	}
	return nil
}

// Node represents a single element in a sparse Merkle tree
// It stores the cryptographic hash of data and the structural information
// required to traverse and reconstruct the tree
type Node struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Value: is the cryptographic hash of the data included in the database
	// the ValueHash is included in the parent hash
	Value []byte `protobuf:"bytes,1,opt,name=Value,proto3" json:"value"` // @gotags: json:"value"
	// LeftChildKey: is the key for the left child node. Nil means no child
	LeftChildKey []byte `protobuf:"bytes,2,opt,name=LeftChildKey,proto3" json:"leftChildKey"` // @gotags: json:"leftChildKey"
	// RightChildKey: is the key for the right child node. Nil means no child
	RightChildKey []byte `protobuf:"bytes,3,opt,name=RightChildKey,proto3" json:"RightChildKey,omitempty"`
	// Key: used for merkle proof generation and verification. It is the compact
	// representation of the node's key bit sequences
	Key []byte `protobuf:"bytes,4,opt,name=Key,proto3" json:"Key,omitempty"`
	// Bitmask: Used for Merkle proof generation and verification. Indicates
	// whether each hash requires the left or right sibling, where 0
	// represents a left sibling and 1 represents a right sibling
	Bitmask       int32 `protobuf:"varint,5,opt,name=Bitmask,proto3" json:"Bitmask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_store_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_store_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_store_proto_rawDescGZIP(), []int{1}
}

func (x *Node) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Node) GetLeftChildKey() []byte {
	if x != nil {
		return x.LeftChildKey
	}
	return nil
}

func (x *Node) GetRightChildKey() []byte {
	if x != nil {
		return x.RightChildKey
	}
	return nil
}

func (x *Node) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *Node) GetBitmask() int32 {
	if x != nil {
		return x.Bitmask
	}
	return 0
}

var File_store_proto protoreflect.FileDescriptor

const file_store_proto_rawDesc = "" +
	"\n" +
	"\vstore.proto\x12\x05types\"6\n" +
	"\bCommitID\x12\x16\n" +
	"\x06height\x18\x01 \x01(\x04R\x06height\x12\x12\n" +
	"\x04root\x18\x02 \x01(\fR\x04root\"\x92\x01\n" +
	"\x04Node\x12\x14\n" +
	"\x05Value\x18\x01 \x01(\fR\x05Value\x12\"\n" +
	"\fLeftChildKey\x18\x02 \x01(\fR\fLeftChildKey\x12$\n" +
	"\rRightChildKey\x18\x03 \x01(\fR\rRightChildKey\x12\x10\n" +
	"\x03Key\x18\x04 \x01(\fR\x03Key\x12\x18\n" +
	"\aBitmask\x18\x05 \x01(\x05R\aBitmaskB&Z$github.com/canopy-network/canopy/libb\x06proto3"

var (
	file_store_proto_rawDescOnce sync.Once
	file_store_proto_rawDescData []byte
)

func file_store_proto_rawDescGZIP() []byte {
	file_store_proto_rawDescOnce.Do(func() {
		file_store_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_store_proto_rawDesc), len(file_store_proto_rawDesc)))
	})
	return file_store_proto_rawDescData
}

var file_store_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_store_proto_goTypes = []any{
	(*CommitID)(nil), // 0: types.CommitID
	(*Node)(nil),     // 1: types.Node
}
var file_store_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_store_proto_init() }
func file_store_proto_init() {
	if File_store_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_store_proto_rawDesc), len(file_store_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_store_proto_goTypes,
		DependencyIndexes: file_store_proto_depIdxs,
		MessageInfos:      file_store_proto_msgTypes,
	}.Build()
	File_store_proto = out.File
	file_store_proto_goTypes = nil
	file_store_proto_depIdxs = nil
}
