// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: account.proto

package fsm

import (
	lib "github.com/canopy-network/canopy/lib"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *****************************************************************************************************
// This file is auto-generated from source files in `/lib/.proto/*` using Protocol Buffers (protobuf)
//
// Protobuf is a language-neutral, platform-neutral serialization format. It allows users
// to define objects in a way that’s both efficient to store and fast to transmit over the network.
// These definitions are compiled into code that *enables different systems and programming languages
// to communicate in a byte-perfect manner*
//
// To update these structures, make changes to the source .proto files, then recompile
// to regenerate this file.
// These auto-generated files are easily recognized by checking for a `.pb.go` ending
// *****************************************************************************************************
// _
// _
// _
// An account is a structure that holds funds and can send or receive transactions using a crypto key pair
// Each account has a unique address and a balance, think a bank account - but managed by the blockchain
// instead of a bank
type Account struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// address: the short version of a public key
	Address []byte `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// amount: the balance of funds the account has
	Amount        uint64 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_account_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{0}
}

func (x *Account) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *Account) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

// A pool is like an account without an owner, holding funds that are managed directly by the blockchain protocol
// It's very similar to an account but instead of an address it has a unique ID and operates based on predefined
// blockchain rules rather than individual control
type Pool struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id: the unique identifier of the pool
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// amount: the balance of funds the pool has
	Amount uint64 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	// LIQUIDITY POOL ONLY
	// ------------------------------------------------------------------------------------
	// points: a list of pool share holders and their respective points
	Points []*lib.PoolPoints `protobuf:"bytes,11,rep,name=points,proto3" json:"poolPoints"` // @gotags: json:"poolPoints"
	// total_pool_points: the total number of pool points
	TotalPoolPoints uint64 `protobuf:"varint,12,opt,name=total_pool_points,json=totalPoolPoints,proto3" json:"totalPoolPoints"` // @gotags: json:"totalPoolPoints"
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Pool) Reset() {
	*x = Pool{}
	mi := &file_account_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pool) ProtoMessage() {}

func (x *Pool) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pool.ProtoReflect.Descriptor instead.
func (*Pool) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{1}
}

func (x *Pool) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Pool) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Pool) GetPoints() []*lib.PoolPoints {
	if x != nil {
		return x.Points
	}
	return nil
}

func (x *Pool) GetTotalPoolPoints() uint64 {
	if x != nil {
		return x.TotalPoolPoints
	}
	return 0
}

// A supply structure keeps track of the total amount of tokens or funds available across the entire blockchain
// It provides a single source of truth for the overall token supply managed by the network
// It conveniently buckets the tokens into useful categories allowing transparency and consistency
// NOTE: 'staked' includes delegations, to calculate stake without delegations, simply staked - delegated_only
type Supply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// total: the total tokens existing in the system - minted tokens are added, burned tokens are removed
	Total uint64 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	// staked: the total locked tokens in the protocol - this includes delegated
	Staked uint64 `protobuf:"varint,2,opt,name=staked,proto3" json:"staked,omitempty"`
	// delegated_only: the total locked tokens that are delegated only
	DelegatedOnly uint64 `protobuf:"varint,3,opt,name=delegated_only,json=delegatedOnly,proto3" json:"delegatedOnly"` // @gotags: json:"delegatedOnly"
	// committee_staked: a list of committees and their 'committed (staked + delegated)' tokens, sorted by stake
	CommitteeStaked []*Pool `protobuf:"bytes,4,rep,name=committee_staked,json=committeeStaked,proto3" json:"committeeStaked"` // @gotags: json:"committeeStaked"
	// committee_delegated_only: a list of committees and their 'delegated only' tokens, sorted by stake
	CommitteeDelegatedOnly []*Pool `protobuf:"bytes,5,rep,name=committee_delegated_only,json=committeeDelegatedOnly,proto3" json:"committeeDelegatedOnly"` // @gotags: json:"committeeDelegatedOnly"
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Supply) Reset() {
	*x = Supply{}
	mi := &file_account_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Supply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Supply) ProtoMessage() {}

func (x *Supply) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Supply.ProtoReflect.Descriptor instead.
func (*Supply) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{2}
}

func (x *Supply) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Supply) GetStaked() uint64 {
	if x != nil {
		return x.Staked
	}
	return 0
}

func (x *Supply) GetDelegatedOnly() uint64 {
	if x != nil {
		return x.DelegatedOnly
	}
	return 0
}

func (x *Supply) GetCommitteeStaked() []*Pool {
	if x != nil {
		return x.CommitteeStaked
	}
	return nil
}

func (x *Supply) GetCommitteeDelegatedOnly() []*Pool {
	if x != nil {
		return x.CommitteeDelegatedOnly
	}
	return nil
}

var File_account_proto protoreflect.FileDescriptor

const file_account_proto_rawDesc = "" +
	"\n" +
	"\raccount.proto\x12\x05types\x1a\tdex.proto\";\n" +
	"\aAccount\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\fR\aaddress\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x04R\x06amount\"\x85\x01\n" +
	"\x04Pool\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x04R\x06amount\x12)\n" +
	"\x06points\x18\v \x03(\v2\x11.types.PoolPointsR\x06points\x12*\n" +
	"\x11total_pool_points\x18\f \x01(\x04R\x0ftotalPoolPoints\"\xdc\x01\n" +
	"\x06Supply\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x04R\x05total\x12\x16\n" +
	"\x06staked\x18\x02 \x01(\x04R\x06staked\x12%\n" +
	"\x0edelegated_only\x18\x03 \x01(\x04R\rdelegatedOnly\x126\n" +
	"\x10committee_staked\x18\x04 \x03(\v2\v.types.PoolR\x0fcommitteeStaked\x12E\n" +
	"\x18committee_delegated_only\x18\x05 \x03(\v2\v.types.PoolR\x16committeeDelegatedOnlyB&Z$github.com/canopy-network/canopy/fsmb\x06proto3"

var (
	file_account_proto_rawDescOnce sync.Once
	file_account_proto_rawDescData []byte
)

func file_account_proto_rawDescGZIP() []byte {
	file_account_proto_rawDescOnce.Do(func() {
		file_account_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_account_proto_rawDesc), len(file_account_proto_rawDesc)))
	})
	return file_account_proto_rawDescData
}

var file_account_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_account_proto_goTypes = []any{
	(*Account)(nil),        // 0: types.Account
	(*Pool)(nil),           // 1: types.Pool
	(*Supply)(nil),         // 2: types.Supply
	(*lib.PoolPoints)(nil), // 3: types.PoolPoints
}
var file_account_proto_depIdxs = []int32{
	3, // 0: types.Pool.points:type_name -> types.PoolPoints
	1, // 1: types.Supply.committee_staked:type_name -> types.Pool
	1, // 2: types.Supply.committee_delegated_only:type_name -> types.Pool
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_account_proto_init() }
func file_account_proto_init() {
	if File_account_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_account_proto_rawDesc), len(file_account_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_account_proto_goTypes,
		DependencyIndexes: file_account_proto_depIdxs,
		MessageInfos:      file_account_proto_msgTypes,
	}.Build()
	File_account_proto = out.File
	file_account_proto_goTypes = nil
	file_account_proto_depIdxs = nil
}
