# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: event.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x65vent.proto\x12\x05types\x1a\x19google/protobuf/any.proto\"\xb7\x01\n\x05\x45vent\x12\x12\n\nevent_type\x18\x01 \x01(\t\x12$\n\x06\x63ustom\x18\x0b \x01(\x0b\x32\x12.types.EventCustomH\x00\x12\x0e\n\x06height\x18[ \x01(\x04\x12\x11\n\treference\x18\\ \x01(\t\x12\x0f\n\x07\x63hainId\x18] \x01(\x04\x12\x14\n\x0c\x62lock_height\x18^ \x01(\x04\x12\x12\n\nblock_hash\x18_ \x01(\x0c\x12\x0f\n\x07\x61\x64\x64ress\x18` \x01(\x0c\x42\x05\n\x03msg\"0\n\x0b\x45ventCustom\x12!\n\x03msg\x18\x01 \x01(\x0b\x32\x14.google.protobuf.AnyB.Z,github.com/canopy-network/go-plugin/contractb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'event_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z,github.com/canopy-network/go-plugin/contract'
  _globals['_EVENT']._serialized_start=50
  _globals['_EVENT']._serialized_end=233
  _globals['_EVENTCUSTOM']._serialized_start=235
  _globals['_EVENTCUSTOM']._serialized_end=283
# @@protoc_insertion_point(module_scope)
